/**
 * System field-marker annotations for the Exeris SDK — per-field markers naming
 * an entity's infrastructure fields (tenancy, identity, optimistic locking,
 * soft delete, audit stamps).
 * <p>This package contains annotations for:
 * <ul>
 *   <li>{@link eu.exeris.sdk.annotation.system.TenantId @TenantId} - Tenant isolation key</li>
 *   <li>{@link eu.exeris.sdk.annotation.system.SharedScope @SharedScope} - Shared-scope key of a
 *       {@code DataScope.UNIVERSE} entity; accompanies {@code @TenantId} rather than replacing it</li>
 *   <li>{@link eu.exeris.sdk.annotation.system.PrimaryKey @PrimaryKey} - Primary key field</li>
 *   <li>{@link eu.exeris.sdk.annotation.system.Version @Version} - Optimistic-locking version</li>
 *   <li>{@link eu.exeris.sdk.annotation.system.SoftDelete @SoftDelete} - Soft-delete flag</li>
 *   <li>{@link eu.exeris.sdk.annotation.system.SoftDeleteTimestamp @SoftDeleteTimestamp} /
 *       {@link eu.exeris.sdk.annotation.system.SoftDeletedBy @SoftDeletedBy} - Soft-delete audit</li>
 *   <li>{@link eu.exeris.sdk.annotation.system.AuditCreatedAt @AuditCreatedAt} /
 *       {@link eu.exeris.sdk.annotation.system.AuditCreatedBy @AuditCreatedBy} /
 *       {@link eu.exeris.sdk.annotation.system.AuditUpdatedAt @AuditUpdatedAt} /
 *       {@link eu.exeris.sdk.annotation.system.AuditUpdatedBy @AuditUpdatedBy} - Audit stamps</li>
 * </ul>
 *
 * <h2>Status — a marker names a field; the entity flag decides whether it exists</h2>
 * <p>A marker says <em>which field</em> plays a system role. It does not switch
 * the role on: whether an entity has a tenant column, audit stamps, soft-delete
 * columns or a version column is decided by the entity-level flags on
 * {@code @ExerisDomain} ({@code dataScope}, {@code audited}, {@code softDelete},
 * {@code versioned}). Three sources can name the field, and all three land in
 * {@code SystemFieldsMetadata}, one field name per role: the marker on the field,
 * the matching {@code @ExerisDomain} field-name override attribute
 * ({@code tenantIdField}, {@code versionField}, {@code softDeleteField}, the
 * audit-field overrides, …), and — when neither is written — the canonical name
 * ({@code tenantId}, {@code version}, {@code createdAt}, …).
 * <ul>
 *   <li><strong>PARTIAL</strong> — {@code @TenantId}, {@code @Version},
 *       {@code @SoftDelete}, {@code @SoftDeleteTimestamp}, {@code @SoftDeletedBy},
 *       {@code @AuditCreatedAt}, {@code @AuditCreatedBy}, {@code @AuditUpdatedAt},
 *       {@code @AuditUpdatedBy}. The {@code exeris-tooling} processor reads each
 *       one and records the annotated field's name in {@code SystemFieldsMetadata},
 *       and the generators use that name in place of the canonical one. Two
 *       declarations are refused where they are written: the same marker on more
 *       than one field, and a marker on one field while the matching override
 *       attribute names another. The markers' own <em>attributes</em>
 *       ({@code @TenantId.autoPopulate}, {@code @Version.useForETag}, …) are not
 *       carried — the record holds a name per role and nothing else — so setting one
 *       changes no emitted output; the processor's {@code -Aexeris.strict} mode
 *       reports each. The {@code -io} reader reads neither these markers nor the
 *       override attributes, so {@code SystemFieldsMetadata} is populated on the
 *       build-time path only, which is what keeps these PARTIAL rather than
 *       LIVE.</li>
 *   <li><strong>RESERVED</strong> — {@code @PrimaryKey}, because no generator
 *       honours a renamed primary key yet ({@code id} is fixed in the schema, the
 *       repository and the generated by-id routes alike); and {@code @SharedScope},
 *       whose {@code sharedScopeField} is for the {@code DataScope.UNIVERSE}
 *       transcription to read, and that transcription is not built.</li>
 * </ul>
 *
 * <p>Where a marker's javadoc lists behaviour, it separates what the entity flag
 * already emits (stamping the tenant on write, soft delete as an update rather
 * than a delete, the optimistic-lock predicate) from the "Target design" its
 * attributes describe. Only the second list is unimplemented.
 *
 * @since 0.9
 */
package eu.exeris.sdk.annotation.system;
