package eu.exeris.sdk.annotation.system;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a field as the primary key.
 * <p>By default, Exeris expects an {@code id} field of type {@code UUID}.
 * Use this annotation to customize primary key behavior.
 *
 * <h2>Usage:</h2>
 * <pre>{@code
 * @Field(label = "Order Number")
 * @PrimaryKey(generated = false)
 * private String orderNumber;  // business key as PK
 * }</pre>
 *
 * @author Exeris SDK Team
 * @version 1.0.0
 * @since 1.0.0
 */
@Target(ElementType. FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface PrimaryKey {

    /**
     * ID generation strategy.
     */
    enum Strategy {
        /** UUID generated by application (default) */
        UUID,
        /** UUID generated by database */
        UUID_DATABASE,
        /** Auto-increment sequence */
        SEQUENCE,
        /** Identity column */
        IDENTITY,
        /** No generation - client provides ID */
        NONE
    }

    /**
     * Whether ID is auto-generated.
     *
     * @return true if generated
     */
    boolean generated() default true;

    /**
     * Generation strategy.
     *
     * @return strategy
     */
    Strategy strategy() default Strategy.UUID;

    /**
     * Sequence name (only for SEQUENCE strategy).
     *
     * @return sequence name
     */
    String sequenceName() default "";

    /**
     * Whether client can provide ID on create.
     * <p>When true and ID is provided, uses client ID instead of generating.
     *
     * @return true if client ID allowed
     */
    boolean allowClientId() default false;
}
