package eu.exeris.sdk.annotation.system;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a field as the primary key.
 * <p>By default, Exeris expects an {@code id} field of type {@code UUID}.
 * Use this annotation to customize primary key behavior.
 *
 * <h2>Usage:</h2>
 * {@snippet lang="java" :
 * @Field(label = "Order Number")
 * @PrimaryKey(generated = false)
 * private String orderNumber;  // business key as PK
 * }
 *
 * <p><strong>Status: RESERVED</strong> — the {@code exeris-tooling} processor does not scan
 * fields for this marker, so writing it changes nothing in the emitted output. What
 * generates the column is the entity-level flag set on {@code @ExerisDomain}, with the
 * field-name override attributes choosing its name. See the package javadoc for the live
 * path.
 *
 * @since 0.1
 */
@Target(ElementType. FIELD)
@Retention(RetentionPolicy.SOURCE)
@Documented
public @interface PrimaryKey {

    /**
     * ID generation strategy.
     */
    enum Strategy {
        /** UUID generated by application (default). */
        UUID,
        /** UUID generated by database. */
        UUID_DATABASE,
        /** Auto-increment sequence. */
        SEQUENCE,
        /** Identity column. */
        IDENTITY,
        /** No generation - client provides ID. */
        NONE
    }

    /**
     * Whether ID is auto-generated.
     *
     * @return true if generated
     */
    boolean generated() default true;

    /**
     * Generation strategy.
     *
     * @return strategy
     */
    Strategy strategy() default Strategy.UUID;

    /**
     * Sequence name (only for SEQUENCE strategy).
     *
     * @return sequence name
     */
    String sequenceName() default "";

    /**
     * Whether client can provide ID on create.
     * <p>When true and ID is provided, uses client ID instead of generating.
     *
     * @return true if client ID allowed
     */
    boolean allowClientId() default false;
}
